#!/bin/bash
#log into ldapclient

sudo apt-get update
sudo apt-get install debconf-utils

echo -e " \
libnss-ldap libnss-ldap/dblogin boolean false
libnss-ldap shared/ldapns/base-dn   string  dc=clemson,dc=cloudlab,dc=us
libnss-ldap libnss-ldap/binddn  string  cn=proxyuser,dc=clemson,dc=us
libnss-ldap libnss-ldap/dbrootlogin boolean true
libnss-ldap libnss-ldap/override    boolean true
libnss-ldap shared/ldapns/ldap-server   string  ldap://192.168.1.1
libnss-ldap libnss-ldap/confperm    boolean false
libnss-ldap libnss-ldap/rootbinddn  string  cn=admin,dc=example,dc=com
libnss-ldap shared/ldapns/ldap_version  select  3
libnss-ldap libnss-ldap/nsswitch    note    \
" | debconf-set-selections

sudo export DEBIAN_FRONTEND=noninteractive apt install -y libnss-ldap libpam-ldap ldap-utils
